name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}

          script: |
            cd ~/pbl-project/jobanalytic-v2
            git pull origin main

            docker restart job-analytic-v2-app
            docker restart nginx-job
